---
- name: ensure packages are installed
  apt:
    update_cache: yes
    name: "{{item}}"
  with_items:
    - python3
    - python3-dev
    - python3-setuptools
    - build-essential
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - graphviz
    - libpq-dev
    - libssl-dev
    - zlib1g-dev
    - python3-pip
    - virtualenv
    - supervisor

- name: "ensure {{ netbox_install_directory }} exists"
  file:
    path: "{{ netbox_install_directory }}"
    state: directory
    mode: 0755

- name: "ensure netbox {{ netbox_version }} source is present"
  unarchive:
    src: "https://github.com/digitalocean/netbox/archive/v{{ netbox_version }}.tar.gz"
    dest: "{{ netbox_install_directory }}"
    remote_src: yes

- name: "ensure netbox {{ netbox_version }} is linked to {{ netbox_install_directory }}/netbox"
  file:
    src: "{{ netbox_install_directory }}/netbox-{{ netbox_version }}"
    dest: "{{ netbox_install_directory }}/netbox"
    state: link
  notify: "update netbox"

- name: ensure python dependancies are installed in virtualenv
  pip:
    requirements: "{{ netbox_install_directory }}/netbox/requirements.txt"
    virtualenv: "{{ netbox_install_directory }}/netbox"
    virtualenv_python: "{{ python_command }}"

- name: ensure configuration.py is present
  template:
    src: configuration.py.j2
    dest: "{{ netbox_install_directory }}/netbox/netbox/netbox/configuration.py"
  notify: "update netbox"

- name: ensure naplam is installed in virtualenv
  pip:
    name: napalm
    virtualenv: "{{ netbox_install_directory }}/netbox"
    virtualenv_python: "{{ python_command }}"

- name: ensure gunicorn is installed in virtualenv
  pip:
    name: gunicorn
    virtualenv: "{{ netbox_install_directory }}/netbox"
    virtualenv_python: "{{ python_command }}"

- name: ensure gunicorn config is present
  template:
    src: gunicorn_config.py.j2
    dest: "{{ netbox_install_directory }}/netbox/gunicorn_config.py"
  notify: "restart supervisor"

- name: ensure supervisor config is present
  template:
    src: supervisor_netbox.conf.j2
    dest: /etc/supervisor/conf.d/netbox.conf
  notify: "restart supervisor"

